version: '3.9'

services:
  db:
    image: postgres:13.1-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    command: gunicorn fuels.wsgi:application  --bind 0:8000 --reload
    volumes:
      - ../backend/:/usr/src/app/
      - static_volume:/usr/src/app/files/static/
    env_file:
      - ./.env
    depends_on:
      - db
  # celery:
  #   build: 
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   command: celery -A fuels24 worker  --loglevel INFO
  #   volumes:
  #     - ../backend/:/usr/src/app/
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - db

  # redis:
  #   image: redis:6.0.10-alpine
  
  nginx:
    image: nginx:1.21.1
    ports:
      - 8001:80
    volumes:
      - ../backend/files/static:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    restart: always
    depends_on:
      - backend
volumes:
  postgres_data:
  static_volume:
